tree: main.cpp
	g++ -otree.bin -g *.h *.cpp
clean:
	rm tree.bin
commit:
	mkdir -p /media/DATA/pile/projects/git/IMCS/cpp/tree	cp *.cpp /media/DATA/pile/projects/git/IMCS/cpp/tree
	cp test.h /media/DATA/pile/projects/git/IMCS/cpp/tree
	cp Makefile /media/DATA/pile/projects/git/IMCS/cpp/tree

