java/matrix: Main.java
	javac -g *.java
clean:
	rm java.bin
commit:
	mkdir -p /media/DATA/pile/projects/git/IMCS/cpp/java/matrix	cp *.java /media/DATA/pile/projects/git/IMCS/cpp/java/matrix
	cp test.h /media/DATA/pile/projects/git/IMCS/cpp/java/matrix
	cp Makefile /media/DATA/pile/projects/git/IMCS/cpp/java/matrix

