complex/simple/: main.cpp
	g++ -ocomplex.bin -g *.cpp
clean:
	rm complex.bin
commit:
	mkdir -p /media/DATA/pile/projects/git/IMCS/cpp/complex/simple/
	cp *.cpp /media/DATA/pile/projects/git/IMCS/cpp/complex/simple/
	cp *.h /media/DATA/pile/projects/git/IMCS/cpp/complex/simple/
	cp Makefile /media/DATA/pile/projects/git/IMCS/cpp/complex/simple/

